# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
change-id = 9999999

[rust]
codegen-backends = ["llvm"]
deny-warnings = false
llvm-bitcode-linker = false

[llvm]
cflags = "-march=native"
cxxflags = "-march=native"
static-libstdcpp = true
download-ci-llvm = false
link-shared = false
# thin-lto = true

[build]
docs = false
extended = false
tools = []
# host = ["wasm32-wasip1-threads", "x86_64-unknown-linux-gnu"]
host = ["wasm32-wasip1-threads"]
# target = ["x86_64-unknown-linux-gnu", "wasm32-wasip1-threads"]
target = ["wasm32-wasip1-threads"]
cargo-native-static = true

[install]
prefix = "dist"
sysconfdir = "etc"

# [target.'wasm32-wasi']
# wasi-root = "wasi-sdk-22.0/share/wasi-sysroot"
# linker = "wasi-sdk-22.0/bin/clang"
# # codegen-backends = ["cranelift"]
# codegen-backends = ["llvm"]
# # This value is failed to compile by rustc
# # rustflags = [
# #     "-C",
# #     "link-arg=-lwasi-emulated-mman",
# #     "-C",
# #     "link-arg=-Wl,--max-memory=4294967296",
# #     "-C",
# #     "link-arg=-Wl,-z,stack-size=1048576",
# #     "-C",
# #     "link-arg=-Wl,--stack-first",
# #     "-C",
# #     "link-arg=-flto",
# #     "-C",
# #     "link-arg=-Wl,--strip-all",
# # ]

[target.'wasm32-wasip1-threads']
wasi-root = "wasi-sdk-22.0/share/wasi-sysroot"
# linker = "wasi-sdk-22.0/bin/clang"
linker = "./wrapper_linker.sh"
# codegen-backends = ["cranelift"]
codegen-backends = ["llvm"]

[target.'x86_64-unknown-linux-gnu']
cc = "gcc"
