# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
change-id = 9999999

[rust]
codegen-backends = ["llvm"]
deny-warnings = false
llvm-bitcode-linker = false

[build]
docs = false
extended = false
tools = []
host = ["wasm32-wasip1-threads"]
target = ["x86_64-unknown-linux-gnu", "wasm32-wasip1-threads"]

[install]
prefix = "dist"
sysconfdir = "etc"

[target.'wasm32-wasi']
wasi-root = "wasi-sdk-22.0/share/wasi-sysroot"
linker = "wasi-sdk-22.0/bin/clang"
# codegen-backends = ["cranelift"]

[target.'wasm32-wasip1-threads']
wasi-root = "wasi-sdk-22.0/share/wasi-sysroot"
linker = "wasi-sdk-22.0/bin/clang"
# codegen-backends = ["cranelift"]

[target.'x86_64-unknown-linux-gnu']
cc = "gcc"
