use std::panic;
use std::path::PathBuf;
use std::sync::Arc;

use rustc_data_structures::flock;
use tracing::instrument;

pub use self::dep_node::{DepKind, DepKindVTable, DepNode, WorkProductId, dep_kind_from_label};
pub use self::dep_node_key::DepNodeKey;
pub use self::graph::{
    DepGraph, DepGraphData, DepNodeIndex, QuerySideEffect, TaskDepsRef, WorkProduct,
    WorkProductMap, hash_result,
};
use self::graph::{MarkFrame, print_markframe_trace};
pub use self::retained::RetainedDepGraph;
pub use self::serialized::{SerializedDepGraph, SerializedDepNodeIndex};
pub use crate::dep_graph::debug::{DepNodeFilter, EdgeFilter};
pub use crate::ty::print::with_reduced_queries;
use crate::ty::{self, TyCtxt};

mod debug;
pub(crate) mod dep_node;
mod dep_node_key;
mod edges;
mod graph;
mod retained;
mod serialized;

/// Holds data on the current incremental compilation session, if there is one.
pub struct IncrCompSession {
    /// The directory from which cached data of a previous session can be read.
    pub old_session_directory: Option<flock::LockedDir>,
    /// The directory to which cached data for the current session can be
    /// written to.
    pub new_session_directory: flock::LockedDir,
    borrows: Arc<()>,
}

impl IncrCompSession {
    pub fn new(
        old_session_directory: Option<flock::LockedDir>,
        new_session_directory: flock::LockedDir,
    ) -> Self {
        IncrCompSession { old_session_directory, new_session_directory, borrows: Arc::new(()) }
    }

    pub fn borrow(&self) -> BorrowedIncrCompSession {
        BorrowedIncrCompSession {
            old_session_directory: self.old_session_directory.as_deref().map(ToOwned::to_owned),
            new_session_directory: (&*self.new_session_directory).to_owned(),
            _borrows: Arc::clone(&self.borrows),
        }
    }
}

impl Drop for IncrCompSession {
    fn drop(&mut self) {
        // Check that there are no workers threads remaining that use the incr
        // comp session before we unlock the old and new session dir. If there
        // does exist a worker thread, there is not much we can do, but at
        // least we will unconditionally complain rather than the worker thread
        // sometimes crashing depending on what other rustc instances run.
        assert!(
            Arc::strong_count(&self.borrows) == 1,
            "Incr comp session dropped while there are still references",
        );
    }
}

/// A runtime tracked borrow of the incr comp session. Can be sent to worker threads.
pub struct BorrowedIncrCompSession {
    pub old_session_directory: Option<PathBuf>,
    pub new_session_directory: PathBuf,
    _borrows: Arc<()>,
}

/// Describes the contents of the fingerprint generated by a given query.
///
/// This is mainly for determining whether and how we can reconstruct a key
/// from the fingerprint.
#[derive(Debug, PartialEq, Eq, Copy, Clone)]
pub enum KeyFingerprintStyle {
    /// The fingerprint is actually a DefPathHash.
    DefPathHash,
    /// The fingerprint is actually a HirId.
    HirId,
    /// Query key was `()` or equivalent, so fingerprint is just zero.
    Unit,
    /// The fingerprint is an opaque hash, and a key cannot be reconstructed from it.
    Opaque,
}

impl KeyFingerprintStyle {
    /// True if a key can _potentially_ be recovered from a key fingerprint
    /// with this style.
    ///
    /// For some key types, recovery is possible but not guaranteed.
    #[inline]
    pub const fn is_maybe_recoverable(self) -> bool {
        match self {
            KeyFingerprintStyle::DefPathHash
            | KeyFingerprintStyle::Unit
            | KeyFingerprintStyle::HirId => true,
            KeyFingerprintStyle::Opaque => false,
        }
    }
}

/// Execute the operation with provided dependencies.
fn with_deps<OP, R>(task_deps: TaskDepsRef<'_>, op: OP) -> R
where
    OP: FnOnce() -> R,
{
    ty::tls::with_context(|icx| {
        let icx = ty::tls::ImplicitCtxt { task_deps, ..*icx };
        ty::tls::enter_context(&icx, op)
    })
}

/// Access dependencies from current implicit context.
fn read_deps<OP>(op: OP)
where
    OP: for<'a> FnOnce(TaskDepsRef<'a>),
{
    ty::tls::with_context_opt(|icx| {
        let Some(icx) = icx else { return };
        op(icx.task_deps)
    })
}

impl<'tcx> TyCtxt<'tcx> {
    #[inline]
    pub fn dep_kind_vtable(self, dk: DepKind) -> &'tcx DepKindVTable<'tcx> {
        &self.query_system.dep_kind_vtables[dk.as_usize()]
    }

    #[inline(always)]
    pub fn key_fingerprint_style(self, kind: DepKind) -> KeyFingerprintStyle {
        self.dep_kind_vtable(kind).key_fingerprint_style
    }

    /// Try to force a dep node to execute and see if it's green.
    ///
    /// Returns true if the query has actually been forced. It is valid that a query
    /// fails to be forced, e.g. when the query key cannot be reconstructed from the
    /// dep-node or when the query kind outright does not support it.
    #[inline]
    #[instrument(skip(self, frame), level = "debug")]
    fn try_force_from_dep_node(
        self,
        dep_node: DepNode,
        prev_index: SerializedDepNodeIndex,
        frame: &MarkFrame<'_>,
    ) -> bool {
        if let Some(force_fn) = self.dep_kind_vtable(dep_node.kind).force_from_dep_node_fn {
            match panic::catch_unwind(panic::AssertUnwindSafe(|| {
                force_fn(self, dep_node, prev_index)
            })) {
                Err(value) => {
                    if !value.is::<rustc_errors::FatalErrorMarker>() {
                        print_markframe_trace(&self.dep_graph, frame);
                    }
                    panic::resume_unwind(value)
                }
                Ok(query_has_been_forced) => query_has_been_forced,
            }
        } else {
            false
        }
    }
}
