name: Build rustc for Redox OS

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Setup Redox OS build toolchain
        run: |
          mkdir .redoxer
          docker pull redoxos/redoxer
          docker run -w "/foo" -v "$(pwd)/.redoxer:/foo/.redoxer" -e "HOME=/foo" redoxos/redoxer redoxer toolchain
          ls -lR .redoxer

      - name: Build
        run: |
          echo "nightly-2021-08-05" > rust-toolchain
          cat > config.toml <<EOF
          changelog-seen = 2
          
          [llvm]
          download-ci-llvm = true
          #ninja = false

          [build]
          host = ["x86_64-unknown-redox"]
          target = ["x86_64-unknown-redox"]
          cargo = "$(rustup which cargo)"
          rustc = "$(rustup which rustc)"
          local-rebuild = true
          docs = false
          
          [install]
          prefix = "redox_rustc"
          
          [rust]
          codegen-backends = ["llvm", "cranelift"]
          deny-warnings = false

          [target.x86_64-unknown-redox]
          cc = "$(pwd)/.redoxer/toolchain/bin/x86_64-unknown-redox-gcc"
          linker = "$(pwd)/.redoxer/toolchain/bin/x86_64-unknown-redox-gcc"

          [dist]

          EOF
          cat config.toml
          rustup run nightly-2021-08-05 ./x.py install
          ls -lR redox_rustc

      - name: Package rustc
        run: tar cvfJ redox_rustc.tar.xz redox_rustc

      - name: Upload rustc
        uses: actions/upload-artifact@v2
        with:
          name: redox_rustc
          path: redox_rustc.tar.xz
