name: Build rustc for Redox OS

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Redox OS build toolchain
        run: |
          mkdir .redoxer
          docker pull redoxos/redoxer
          docker run -w "/foo" -v "$(pwd)/.redoxer:/foo/.redoxer" -e "HOME=/foo" redoxos/redoxer redoxer toolchain
          ls -lR .redoxer

      - name: Setup rustc_codegen_cranelift
        run: |
          git clone https://github.com/bjorn3/rustc_codegen_cranelift/
          pushd rustc_codegen_cranelift
          ./y.rs build
          popd
          ls -lR rustc_codegen_cranelift/build
          cp rustc_codegen_cranelift/rust-toolchain ./

      - name: Build
        run: ./x.py build
